###################  项目启动端口  ###################
server:
  port: 8011

#  cloud:
#    config:
#      discovery:
#        enabled: true
#        service-id: config-server
#      profile: prod
###################  项目注册入口  ###################
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true

##########################################################
##################  spring配置 data配置  ##################
##########################################################
spring:
  application:
    name: user-server-1
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
      enabled: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    readSize: 2
    write:
      user-center:
        url: jdbc:mysql://47.98.139.112:3306/user_center?autoReconnect=true&failOverReadOnly=false&useUnicode=true&amp;characterEncoding=utf-8
        driver-class-name: com.mysql.jdbc.Driver
        username: sunwukong
        password: J8bWDX+3LH5WMN+98F1g1g==
        minIdle: 5
        maxActive: 100
        initialSize: 10
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 50
        removeAbandoned: true
        filters: stat
      marketing:
        url: jdbc:mysql://47.98.139.112:3306/marketing?useUnicode=true&amp;characterEncoding=utf-8
        driver-class-name: com.mysql.jdbc.Driver
        username: sunwukong
        password: J8bWDX+3LH5WMN+98F1g1g==
        minIdle: 5
        maxActive: 100
        initialSize: 10
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 50
        removeAbandoned: true
        filters: stat
      chat-mess:
        url: jdbc:mysql://47.98.139.112:3306/chat_mess?useUnicode=true&amp;characterEncoding=utf-8
        driver-class-name: com.mysql.jdbc.Driver
        username: sunwukong
        password: J8bWDX+3LH5WMN+98F1g1g==
        minIdle: 5
        maxActive: 100
        initialSize: 10
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 50
        removeAbandoned: true
        filters: stat
    read:
      user-center:
        url: jdbc:mysql://47.96.98.127:3306/user_center?useUnicode=true&amp;characterEncoding=utf-8
        driver-class-name: com.mysql.jdbc.Driver
        username: admin
        password: sunwukong123
        minIdle: 5
        maxActive: 100
        initialSize: 10
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 50
        removeAbandoned: true
        filters: stat
      marketing:
        url: jdbc:mysql://47.96.98.127:3306/marketing?useUnicode=true&amp;characterEncoding=utf-8
        driver-class-name: com.mysql.jdbc.Driver
        username: admin
        password: sunwukong123
        minIdle: 5
        maxActive: 100
        initialSize: 10
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 50
        removeAbandoned: true
        filters: stat
      chat-mess:
        url: jdbc:mysql://47.96.98.127:3306/chat_mess?useUnicode=true&amp;characterEncoding=utf-8
        driver-class-name: com.mysql.jdbc.Driver
        username: admin
        password: sunwukong123
        minIdle: 5
        maxActive: 100
        initialSize: 10
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 50
        removeAbandoned: true
        filters: stat
###################  数据日志配置  ###################
logging:
  #file: logs/server-user.log
  level:
    net.sunwukong.www.user.server.dao.usercenter.read: trace
    net.sunwukong.www.user.server.dao.usercenter.write: trace
    net.sunwukong.www.user.server.dao.chatmess.write: trace
    net.sunwukong.www.user.server.dao.chatmess.read: trace
    net.sunwukong.www.user.server.dao.marketing.write: trace
    net.sunwukong.www.user.server.dao.marketing.read: trace

ribbon:
  eureka:
    enabled: true
  #：请求处理的超时时间
  ReadTimeout: 60000
  #：请求连接的超时时间
  ConnectTimeout: 60000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 6000